### ISSUE TITLE
create arweave wallet account  using go lang.

### ISSUE THREAD

**Issue by bhaagiKenpachi** [everFinance/goar#38]
Is it possible to create arweave wallet account ?. Below is the scenario.

User can provide seed phrase if exists or create a new seed phrase to create new arweave wallet account.

**Comment by kevin-zhangzh** [comment]
We have  implement the creation of arweave wallet, you can create a keyfile through goar, the file name is the address corresponding to this keyfile, you can import it to other wallets like arconnect.（it's coming soon）

We cannot implement the seed phrase part for the following reasons:
- golang can indeed generate keyfile and key pair through seed phrase, but it is not compatible with js side.
- This means that you will get different key pairs on golang and js using the same seed phrase.
For example, you generate the seed phrase in goar and get the keyfile, but when you import these seed phrases to arconnect (which is implemented in js), you will get a different address.

The process of generating a RSA key pair from seed phrase is as follows:
seed phrase -> random seed -> PRNG(pseudo random number generator)-> find p,q -> generate keyPair by p,q.
We can be fully compatible with js in the first three steps, so we guess that the cause of this problem is that golang and js have slightly different implementations of finding large prime numbers p and q in the RSA algorithm. That's a big issue.

**Comment by bhaagiKenpachi** [comment]
@kevin-zhangzh Ok thanks for implementing. I'm good with the reasons.
